worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    proxy_buffering off;
    fastcgi_buffering off;
    output_buffers 1 1m;
    client_body_buffer_size 512k;
    client_max_body_size 0;


    server {
        listen 80;
        server_name localhost;

        root   C:/gameloft-cdn/public;
        index  index.php;

        location /cdn/ {
            sendfile on;
            directio 16m;
            access_log off;
        }


        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            include        fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            fastcgi_buffering off;
        }
    }
}
